### ISSUE TITLE
S17: As a player, I would like to view my profile page which includes the accumulated statistics of my playing history

### ISSUE THREAD

**Issue by DTaskiran** [sopra-fs24-group-28/spotify-memory-server#155]
### Acceptance Criteria 
- [x] From the lobby overview, a user can navigate to their profile page
- [x] The profile page displays their account data, including name and profile picture
- [x] The profile page displays their game history statistics

### Development Tasks
- [x] sopra-fs24-group-28/spotify-memory-client#70
- [x] sopra-fs24-group-28/spotify-memory-client#71
- [x] sopra-fs24-group-28/spotify-memory-server#158
