### ISSUE TITLE
S3: As a user, I want to be able to log in with my credentials to access the game

### ISSUE THREAD

**Issue by DTaskiran** [sopra-fs24-group-28/spotify-memory-server#18]
## Acceptance Criteria
- [x] Upon successful login, the home page is shown
- [x] Upon failure (incorrect credentials, etc.) an error is displayed and the user is redirected to the login screen
- [x] The login process is secure, including the transmission and persistence of credentials 
- [x] Upon successful login, the user session remains active for a reasonable duration

## Development Tasks
- [x] sopra-fs24-group-28/spotify-memory-client#35
- [x] sopra-fs24-group-28/spotify-memory-client#34
- [x] sopra-fs24-group-28/spotify-memory-server#34
- [x] #91
- [x] #88
- [x] #87
- [x] sopra-fs24-group-28/spotify-memory-client#33
- [x] sopra-fs24-group-28/spotify-memory-client#32
