### ISSUE TITLE
S6: As a logged-in user, I want to have a home page with a list of all active game lobbies in order to gain an overview of current activity. 

### ISSUE THREAD

**Issue by DTaskiran** [sopra-fs24-group-28/spotify-memory-server#19]
## Acceptance Criteria
- [x] A users can see a list of all active lobbies on the home page
- [x] Each listed lobby includes a lobby identifier (e.g. lobby name) and number of players in the lobby
- [x] Users can select a lobby to join from the home page

## Development Tasks
- [x] sopra-fs24-group-28/spotify-memory-client#29
- [x] sopra-fs24-group-28/spotify-memory-server#41
- [x] #98
- [x] sopra-fs24-group-28/spotify-memory-client#28
