### ISSUE TITLE
S4: As a logged-in user, I want to be able to log out of my account securely to protect my privacy. 

### ISSUE THREAD

**Issue by DTaskiran** [sopra-fs24-group-28/spotify-memory-server#20]
## Acceptance Criteria 
- [x] Upon successful logout, the user is notified and redirected to the login screen
- [x] Upon failure, an error is displayed and the user is asked to retry
- [x] Upon successful logout, the lobbies hosted by the user are destroyed and the guests informed and redirected
- [x] The option to logout is reasonably accessible from anywhere within the platform

## Development Tasks
- [x] sopra-fs24-group-28/spotify-memory-client#37
- [x] sopra-fs24-group-28/spotify-memory-client#31
- [x] sopra-fs24-group-28/spotify-memory-server#38
- [x] sopra-fs24-group-28/spotify-memory-client#30
