### ISSUE TITLE
S7: As a logged-in user, I want to be able to create a lobby in order to host a game. 

### ISSUE THREAD

**Issue by DTaskiran** [sopra-fs24-group-28/spotify-memory-server#21]
## Acceptance Criteria
- [x] The host (creator of lobby) can set specifications for the lobby
- [x] After launching the lobby, the host can see a lobby screen which they can see a list of players who have already joined 
- [ ] ~The host can send invitation links to the lobby~

## Development Tasks
- [x] sopra-fs24-group-28/spotify-memory-client#27
- [x] sopra-fs24-group-28/spotify-memory-client#26
- [x] #89
- [x] sopra-fs24-group-28/spotify-memory-server#45
- [x] sopra-fs24-group-28/spotify-memory-client#25
- [x] sopra-fs24-group-28/spotify-memory-client#24
- [x] sopra-fs24-group-28/spotify-memory-server#48
- [x] #95
- [x] #101
