### ISSUE TITLE
S8: As a user, I want to be able to join existing game lobbies as a player to participate in a game.

### ISSUE THREAD

**Issue by DTaskiran** [sopra-fs24-group-28/spotify-memory-server#22]
## Acceptance Criteria
- [x] Logged in users can join lobbies as players 
- [x] Players can leave lobbies before the game starts

## Development Tasks
- [x] sopra-fs24-group-28/spotify-memory-client#23
- [x] sopra-fs24-group-28/spotify-memory-server#50
- [x] sopra-fs24-group-28/spotify-memory-client#22
- [x] sopra-fs24-group-28/spotify-memory-client#21
- [x] sopra-fs24-group-28/spotify-memory-server#53
