### ISSUE TITLE
S9: As a lobby host, I want to be able to start a game from the game lobby in order to enter a round of play.

### ISSUE THREAD

**Issue by DTaskiran** [sopra-fs24-group-28/spotify-memory-server#23]
## Acceptance Criteria
- [x] The host can start the game if at least two players are in the lobby
- [x] Upon starting the game, the lobby closes and no additional players can join
- [ ] ~Upon starting the game, the lobby displays a countdown to the game start~

## Development Tasks
- [x] sopra-fs24-group-28/spotify-memory-client#20
- [x] sopra-fs24-group-28/spotify-memory-server#55
- [x] #99
- [x] sopra-fs24-group-28/spotify-memory-server#56
- [x] #100
- [x] sopra-fs24-group-28/spotify-memory-client#19
- [x] sopra-fs24-group-28/spotify-memory-server#58
