### ISSUE TITLE
S10: As an active player (user whose turn it is), I want to select a card, consume the respective content (e.g. hear song, depending on game mode), then select a second, different card and consume its respective content in order to complete a game turn.

### ISSUE THREAD

**Issue by DTaskiran** [sopra-fs24-group-28/spotify-memory-server#24]
## Acceptance Criteria
- [x] If the two cards match, the player receives two points, the two cards are removed from the table and the same player can replay
- [x] If the two cards don’t match, the player’s turn is over, they become an observing player and the next player’s turn starts
- [x] The active player (only one at a time) can select a card by clicking on it
- [x] The same card cannot be selected twice in the same try
- [x] Observing players cannot make a selection

## Development Tasks
- [x] sopra-fs24-group-28/spotify-memory-client#18
- [x] sopra-fs24-group-28/spotify-memory-client#17
- [x] sopra-fs24-group-28/spotify-memory-server#61
- [x] sopra-fs24-group-28/spotify-memory-client#16
- [x] sopra-fs24-group-28/spotify-memory-server#63
- [x] sopra-fs24-group-28/spotify-memory-server#64
- [x] sopra-fs24-group-28/spotify-memory-client#15
