### ISSUE TITLE
S11: As an observing player (user whose turn it is not), I want to be able to see the selections made by the active player and see the respective content in order to have the same information as all other players.

### ISSUE THREAD

**Issue by DTaskiran** [sopra-fs24-group-28/spotify-memory-server#25]
## Acceptance Criteria
- [x] The observing player(s) can observe which cards are selected by the active player
- [x] The observing player(s) can consume the content at the same time as the active player
- [x] The observing player(s) cannot select cards

## Development Tasks
- [x] sopra-fs24-group-28/spotify-memory-client#62
- [x] sopra-fs24-group-28/spotify-memory-client#14
- [x] sopra-fs24-group-28/spotify-memory-server#67
