### ISSUE TITLE
S14: As a player, I want to have the option to leave the current lobby after a game has ended in order to return to the home page.

### ISSUE THREAD

**Issue by DTaskiran** [sopra-fs24-group-28/spotify-memory-server#28]
## Acceptance Criteria
- [x] The action redirects the player to the home page, and leaves the user logged in
- [x] A host leaving the lobby closes the lobby and redirects all users to the home page
- [x] A non-host leaving the lobby is redirected to the home page while the rest of the lobby stays unaffected
- [x] The leaving user’s state is updated such that they can join new games or create a new lobby

## Development Tasks
- [x] sopra-fs24-group-28/spotify-memory-client#10
- [x] sopra-fs24-group-28/spotify-memory-client#36
- [x] sopra-fs24-group-28/spotify-memory-server#73
- [x] sopra-fs24-group-28/spotify-memory-server#74
- [x] sopra-fs24-group-28/spotify-memory-client#9
- [x] sopra-fs24-group-28/spotify-memory-client#8
