### ISSUE TITLE
S15: As a host, I want to be able to restart the game with the same players that are currently in this game lobby.

### ISSUE THREAD

**Issue by DTaskiran** [sopra-fs24-group-28/spotify-memory-server#29]
## Acceptance Criteria
- [x] The host can click a button that restarts the game
- [x] The restart will be performed ~after a countdown giving users the option to leave the game, without affecting their personal scores~ immediately
- [x] ~During the countdown, the host can abort the restart~
- [x] All users are notified of the host actions
- [x] ~Once the countdown is over~ Once the host restarts, game starts automatically with all the users still in the lobby

## Development Tasks
- [x] sopra-fs24-group-28/spotify-memory-client#7
- [x] sopra-fs24-group-28/spotify-memory-client#6
- [x] sopra-fs24-group-28/spotify-memory-client#5
- [x] sopra-fs24-group-28/spotify-memory-server#81
- [x] sopra-fs24-group-28/spotify-memory-server#79
- [x] sopra-fs24-group-28/spotify-memory-client#4
