### ISSUE TITLE
S16: As a player (both active and observer) in an active game, I want to be able to receive and use power-ups during the to affect the game for both myself and my opponents.

### ISSUE THREAD

**Issue by DTaskiran** [sopra-fs24-group-28/spotify-memory-server#30]
## Acceptance Criteria
- [x] Players with a streak of multiple correctly matched pairs have a chance to receive doubled points for the ongoing streak of matches
- [x] ~Players who play a particularly quick turn have the chance to reduce the turn timer for their opponents~

## Development Tasks
- [x] sopra-fs24-group-28/spotify-memory-client#3
- [x] sopra-fs24-group-28/spotify-memory-server#84
- [x] sopra-fs24-group-28/spotify-memory-server#85
- [x] sopra-fs24-group-28/spotify-memory-server#86
