### ISSUE TITLE
Make an appropriate request to the Spotify Web API from the backend and broadcast result to Game WebSocket connections

### ISSUE THREAD

**Issue by DTaskiran** [sopra-fs24-group-28/spotify-memory-server#63]
**Subtasks**
 
- [x] (SpotifyService) Function that sets a given song for a given player
- [ ] (CardCollection) Function to check matching card
- [ ] (GameService) Function to check whether game is finished
- [ ] (GameService) Function to create GameChangesDTO Event when card has been picked
